
services:
  postgres:
    image: postgres:latest
    container_name: uicm-postgres
    environment:
      POSTGRES_USER: uidevteam
      POSTGRES_PASSWORD: uidevpass
      POSTGRES_DB: uidevdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: uicm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres-data: