version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: uicm-postgres
    environment:
      POSTGRES_USER: uidevteam
      POSTGRES_PASSWORD: uidevpass
      POSTGRES_DB: uidevdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
